auto:	          true

markdown:         rdiscount
pygments:         true
permalink:        /:year/:month/:title/

title:            AlexKong.net
url:              http://alexkong.net
feed:             /atom.xml
author: 孔明
description:      "孔明的博客"
author_info:      <a href="http://alexkong.net/about">孔明</a>

copyright:
    - Design by <a href="http://alexkong.net/about" title="孔明" target="_blank">孔明</a> &copy; Copyright 2012
