markdown: kramdown
pygments: true
plugins: ./_plugins
paginate: 8
permalink:        /:year/:month/:title/

safe: false

#站点基础配置
title: AlexKong.net
description: "孔明的博客"
author: 孔明
author_info: <a href="http://alexkong.net/about">孔明</a>
url: http://localhost:4000
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: http://www.alexkong.net/contact.html
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/pizn/iLotus
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: 孔明
